version: '2'

services:

  pulsar:
      image: apachepulsar/pulsar:2.5.0
      expose:
          - 8080
          - 6650
      environment:
          - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
      command: >
          /bin/bash -c
          "bin/apply-config-from-env.py conf/standalone.conf
          && bin/pulsar standalone"
