name: Prepare Release

on:
    pull_request:
        types:
            - closed
        paths:
            - '.github/project.yml'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    prepare-release:
        name: Prepare Release
        if: ${{ github.event.pull_request.merged == true}}
        uses: smallrye/.github/.github/workflows/prepare-release.yml@main
        secrets: inherit

    after-release:
        name: After release
        needs: prepare-release
        runs-on: ubuntu-latest
        if: ${{ github.event.pull_request.merged == true}}

        steps:
            -   name: Create GitHub App Token
                id: app-token
                uses: actions/create-github-app-token@v2
                with:
                    app-id: ${{ vars.CI_APP_ID }}
                    private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}

            -   name: Checkout
                uses: actions/checkout@v6
                with:
                    ref: ${{ github.ref }}
                    token: ${{steps.app-token.outputs.token}}

            -   name: Java setup
                uses: actions/setup-java@v5
                with:
                    java-version: '21'
                    distribution: 'temurin'
                    cache: maven

            -   name: Tools setup
                run: |
                    curl -s "https://get.sdkman.io" | bash
                    source ~/.sdkman/bin/sdkman-init.sh && sdk install jbang

            -   name: Get GitHub App User ID
                id: get-user-id
                run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
                env:
                    GH_TOKEN: ${{ steps.app-token.outputs.token }}

            -   name: Configure Git author
                run: |
                    git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
                    git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'

            -   name: Update files
                shell: bash -ieo pipefail {0}
                run: |
                    echo "âœ… Clear RevAPI justifications, if any"
                    jbang .build/CompatibilityUtils.java clear
                    if [[ $(git diff --stat) != '' ]]; then
                      git add -A
                      git status
                      git commit -m "[POST-RELEASE] - Clearing breaking change justifications"
                      git push
                    else
                      echo "No justifications cleared"
                    fi
