# usage: antora generate antora-playbook.yml
site:
    title: SmallRye Reactive Messaging
    start_page: smallrye-reactive-messaging::index.adoc

content:
    sources:
        - url: ../
          start_path: documentation/target/antora
          branches: HEAD
ui:
    bundle:
        url: ./ui-bundle.zip

